# Generated by Django 6.0.3 on 2026-03-08 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('min_limit', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('max_limit', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('fixed_charge', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('rate', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('percent_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Withdraw Method',
                'db_table': 'withdraw_methods',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('currency', models.CharField(blank=True, max_length=40, null=True)),
                ('rate', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('charge', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('trx', models.CharField(blank=True, max_length=40, null=True)),
                ('final_amount', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('after_charge', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('withdraw_information', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(2, 'Pending'), (1, 'Approved'), (3, 'Rejected')], default=2)),
                ('admin_feedback', models.TextField(blank=True, null=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='accounts.organizer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='orders.withdrawmethod')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('payment_status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Failed'), (3, 'Refunded')], default=0)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Cancelled')], default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'payment_status'], name='orders_user_id_113dd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('charge', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('post_balance', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('trx_type', models.CharField(choices=[('+', 'Credit'), ('-', 'Debit')], max_length=40)),
                ('trx', models.CharField(blank=True, max_length=40, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=40, null=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.organizer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trx'], name='transaction_trx_8216a8_idx')],
            },
        ),
    ]
