/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-events': RouteRecordInfo<'admin-events', '/admin/events', Record<never, never>, Record<never, never>>,
    'admin-events-add': RouteRecordInfo<'admin-events-add', '/admin/events/add', Record<never, never>, Record<never, never>>,
    'admin-events-categories': RouteRecordInfo<'admin-events-categories', '/admin/events/categories', Record<never, never>, Record<never, never>>,
    'admin-events-locations': RouteRecordInfo<'admin-events-locations', '/admin/events/locations', Record<never, never>, Record<never, never>>,
    'admin-organizers': RouteRecordInfo<'admin-organizers', '/admin/organizers', Record<never, never>, Record<never, never>>,
    'admin-organizers-id-edit': RouteRecordInfo<'admin-organizers-id-edit', '/admin/organizers/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-organizers-add': RouteRecordInfo<'admin-organizers-add', '/admin/organizers/add', Record<never, never>, Record<never, never>>,
    'admin-profile': RouteRecordInfo<'admin-profile', '/admin/profile', Record<never, never>, Record<never, never>>,
    'admin-settings-tab?': RouteRecordInfo<'admin-settings-tab?', '/admin/settings/:tab?', { tab?: ParamValueZeroOrOne<true> }, { tab?: ParamValueZeroOrOne<false> }>,
    'admin-transactions': RouteRecordInfo<'admin-transactions', '/admin/transactions', Record<never, never>, Record<never, never>>,
    'admin-transactions-deposits': RouteRecordInfo<'admin-transactions-deposits', '/admin/transactions/deposits', Record<never, never>, Record<never, never>>,
    'admin-transactions-withdrawals': RouteRecordInfo<'admin-transactions-withdrawals', '/admin/transactions/withdrawals', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin-users-add': RouteRecordInfo<'admin-users-add', '/admin/users/add', Record<never, never>, Record<never, never>>,
    'cart': RouteRecordInfo<'cart', '/cart', Record<never, never>, Record<never, never>>,
    'checkout': RouteRecordInfo<'checkout', '/checkout', Record<never, never>, Record<never, never>>,
    'checkout-success': RouteRecordInfo<'checkout-success', '/checkout/success', Record<never, never>, Record<never, never>>,
    'events-id': RouteRecordInfo<'events-id', '/events/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'organizer-dashboard': RouteRecordInfo<'organizer-dashboard', '/organizer/dashboard', Record<never, never>, Record<never, never>>,
    'organizer-events': RouteRecordInfo<'organizer-events', '/organizer/events', Record<never, never>, Record<never, never>>,
    'organizer-events-create': RouteRecordInfo<'organizer-events-create', '/organizer/events/create', Record<never, never>, Record<never, never>>,
    'organizer-finances': RouteRecordInfo<'organizer-finances', '/organizer/finances', Record<never, never>, Record<never, never>>,
    'organizer-notifications': RouteRecordInfo<'organizer-notifications', '/organizer/notifications', Record<never, never>, Record<never, never>>,
    'organizer-orders': RouteRecordInfo<'organizer-orders', '/organizer/orders', Record<never, never>, Record<never, never>>,
    'organizer-profile': RouteRecordInfo<'organizer-profile', '/organizer/profile', Record<never, never>, Record<never, never>>,
    'organizer-retrait': RouteRecordInfo<'organizer-retrait', '/organizer/retrait', Record<never, never>, Record<never, never>>,
    'organizer-two-fa-verify': RouteRecordInfo<'organizer-two-fa-verify', '/organizer/two-fa-verify', Record<never, never>, Record<never, never>>,
    'payment-success': RouteRecordInfo<'payment-success', '/payment/success', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'two-fa-verify': RouteRecordInfo<'two-fa-verify', '/two-fa-verify', Record<never, never>, Record<never, never>>,
    'user-dashboard': RouteRecordInfo<'user-dashboard', '/user/dashboard', Record<never, never>, Record<never, never>>,
    'user-events': RouteRecordInfo<'user-events', '/user/events', Record<never, never>, Record<never, never>>,
    'user-notifications': RouteRecordInfo<'user-notifications', '/user/notifications', Record<never, never>, Record<never, never>>,
    'user-orders': RouteRecordInfo<'user-orders', '/user/orders', Record<never, never>, Record<never, never>>,
    'user-profile': RouteRecordInfo<'user-profile', '/user/profile', Record<never, never>, Record<never, never>>,
    'user-saved': RouteRecordInfo<'user-saved', '/user/saved', Record<never, never>, Record<never, never>>,
    'user-support': RouteRecordInfo<'user-support', '/user/support', Record<never, never>, Record<never, never>>,
  }
}
