# Generated by Django 6.0.3 on 2026-03-08 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_id', models.IntegerField(default=0)),
                ('code', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('alias', models.CharField(default='NULL', max_length=40)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Enable'), (2, 'Disable')], default=1)),
                ('gateway_parameters', models.JSONField(blank=True, null=True)),
                ('supported_currencies', models.JSONField(blank=True, null=True)),
                ('crypto', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'db_table': 'gateways',
            },
        ),
        migrations.CreateModel(
            name='GatewayCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('currency', models.CharField(blank=True, max_length=40, null=True)),
                ('symbol', models.CharField(blank=True, max_length=40, null=True)),
                ('method_code', models.IntegerField(blank=True, null=True)),
                ('gateway_alias', models.CharField(blank=True, max_length=40, null=True)),
                ('min_amount', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('max_amount', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('percent_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fixed_charge', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('rate', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('gateway_parameter', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gateway Currency',
                'db_table': 'gateway_currencies',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.IntegerField(default=0)),
                ('method_code', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('method_currency', models.CharField(blank=True, max_length=40, null=True)),
                ('charge', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('rate', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('final_amount', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('btc_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('btc_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('trx', models.CharField(blank=True, max_length=40, null=True)),
                ('payment_try', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(2, 'Pending'), (1, 'Success'), (3, 'Cancelled')], default=2)),
                ('from_api', models.BooleanField(default=False)),
                ('admin_feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('success_url', models.CharField(blank=True, max_length=255, null=True)),
                ('failed_url', models.CharField(blank=True, max_length=255, null=True)),
                ('last_cron', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit',
                'db_table': 'deposits',
                'ordering': ['-created_at'],
            },
        ),
    ]
