# Generated by Django 6.0.3 on 2026-03-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('interval', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cron Schedule',
                'db_table': 'cron_schedules',
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('shortcode', models.JSONField(blank=True, null=True)),
                ('support', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Enable'), (2, 'Disable')], default=1)),
            ],
            options={
                'verbose_name': 'Extension',
                'db_table': 'extensions',
            },
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_keys', models.CharField(blank=True, max_length=40, null=True)),
                ('data_values', models.TextField(blank=True, null=True)),
                ('seo_content', models.TextField(blank=True, null=True)),
                ('tempname', models.CharField(blank=True, max_length=40, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Frontend Content',
                'db_table': 'frontends',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(blank=True, max_length=40, null=True)),
                ('cancel_time', models.IntegerField(blank=True, null=True)),
                ('payment_timeout', models.IntegerField(blank=True, null=True)),
                ('event_verification', models.BooleanField(default=False)),
                ('cur_text', models.CharField(blank=True, max_length=40, null=True)),
                ('cur_sym', models.CharField(blank=True, max_length=40, null=True)),
                ('email_from', models.EmailField(blank=True, max_length=40, null=True)),
                ('email_from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_template', models.TextField(blank=True, null=True)),
                ('sms_template', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_body', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_from', models.CharField(blank=True, max_length=255, null=True)),
                ('push_title', models.CharField(blank=True, max_length=255, null=True)),
                ('push_template', models.CharField(blank=True, max_length=255, null=True)),
                ('base_color', models.CharField(blank=True, max_length=40, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=40, null=True)),
                ('mail_config', models.JSONField(blank=True, null=True)),
                ('sms_config', models.JSONField(blank=True, null=True)),
                ('firebase_config', models.JSONField(blank=True, null=True)),
                ('global_shortcodes', models.TextField(blank=True, null=True)),
                ('kv', models.BooleanField(default=False, help_text='KYC verification required')),
                ('ev', models.BooleanField(default=False, help_text='Email verification required')),
                ('en', models.BooleanField(default=False, help_text='Email notifications enabled')),
                ('sv', models.BooleanField(default=False, help_text='SMS verification required')),
                ('sn', models.BooleanField(default=False, help_text='SMS notifications enabled')),
                ('pn', models.BooleanField(default=True, help_text='Push notifications enabled')),
                ('force_ssl', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('secure_password', models.BooleanField(default=False)),
                ('agree', models.BooleanField(default=False)),
                ('multi_language', models.BooleanField(default=True)),
                ('registration', models.BooleanField(default=False)),
                ('organizer_registration', models.SmallIntegerField(default=1)),
                ('active_template', models.CharField(blank=True, max_length=40, null=True)),
                ('socialite_credentials', models.JSONField(blank=True, null=True)),
                ('system_info', models.TextField(blank=True, null=True)),
                ('last_cron', models.DateTimeField(blank=True, null=True)),
                ('available_version', models.CharField(blank=True, max_length=40, null=True)),
                ('system_customized', models.BooleanField(default=False)),
                ('paginate_number', models.IntegerField(default=0)),
                ('currency_format', models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Both'), (2, 'Text Only'), (3, 'Symbol Only')], default=0)),
                ('max_gallery_images', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
                'db_table': 'general_settings',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('image', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('slug', models.CharField(blank=True, max_length=40, null=True)),
                ('tempname', models.CharField(blank=True, max_length=40, null=True)),
                ('secs', models.TextField(blank=True, null=True)),
                ('seo_content', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page',
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'db_table': 'subscribers',
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(blank=True, max_length=40, null=True)),
                ('update_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Update Log',
                'db_table': 'update_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('alias', models.CharField(blank=True, max_length=40, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=True)),
                ('is_default', models.SmallIntegerField(default=1)),
                ('cron_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='cms.cronschedule')),
            ],
            options={
                'verbose_name': 'Cron Job',
                'db_table': 'cron_jobs',
            },
        ),
    ]
