# Generated by Django 6.0.3 on 2026-03-08 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('push_title', models.CharField(blank=True, max_length=255, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('sms_body', models.TextField(blank=True, null=True)),
                ('push_body', models.TextField(blank=True, null=True)),
                ('shortcodes', models.TextField(blank=True, null=True)),
                ('email_status', models.BooleanField(default=True)),
                ('email_sent_from_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email_sent_from_address', models.CharField(blank=True, max_length=40, null=True)),
                ('sms_status', models.BooleanField(default=True)),
                ('sms_sent_from', models.CharField(blank=True, max_length=40, null=True)),
                ('push_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('click_url', models.TextField(blank=True, null=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organizer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'db_table': 'admin_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(blank=True, max_length=40, null=True)),
                ('sent_from', models.CharField(blank=True, max_length=40, null=True)),
                ('sent_to', models.CharField(blank=True, max_length=40, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('notification_type', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('user_read', models.SmallIntegerField(default=0)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='accounts.organizer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
